# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'window.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(432, 431)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.tab_help = QtWidgets.QTabWidget(self.centralwidget)
        self.tab_help.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.tab_help.setTabPosition(QtWidgets.QTabWidget.North)
        self.tab_help.setObjectName("tab_help")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.groupBox = QtWidgets.QGroupBox(self.tab)
        self.groupBox.setGeometry(QtCore.QRect(3, 10, 401, 351))
        self.groupBox.setTitle("")
        self.groupBox.setObjectName("groupBox")
        self.textEdit_message = QtWidgets.QTextEdit(self.groupBox)
        self.textEdit_message.setGeometry(QtCore.QRect(10, 40, 391, 231))
        self.textEdit_message.setObjectName("textEdit_message")
        self.label_message = QtWidgets.QLabel(self.groupBox)
        self.label_message.setGeometry(QtCore.QRect(20, 10, 91, 21))
        self.label_message.setObjectName("label_message")
        self.button_send_message = QtWidgets.QPushButton(self.groupBox)
        self.button_send_message.setGeometry(QtCore.QRect(120, 290, 181, 41))
        self.button_send_message.setObjectName("button_send_message")
        self.tab_help.addTab(self.tab, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.tab_2.setObjectName("tab_2")
        self.groupBox_2 = QtWidgets.QGroupBox(self.tab_2)
        self.groupBox_2.setGeometry(QtCore.QRect(0, 10, 401, 351))
        self.groupBox_2.setTitle("")
        self.groupBox_2.setObjectName("groupBox_2")
        self.horizontalLayoutWidget_2 = QtWidgets.QWidget(self.groupBox_2)
        self.horizontalLayoutWidget_2.setGeometry(QtCore.QRect(10, 20, 381, 41))
        self.horizontalLayoutWidget_2.setObjectName("horizontalLayoutWidget_2")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_2)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_token = QtWidgets.QLabel(self.horizontalLayoutWidget_2)
        self.label_token.setObjectName("label_token")
        self.horizontalLayout_2.addWidget(self.label_token)
        self.lineEdit_token = QtWidgets.QLineEdit(self.horizontalLayoutWidget_2)
        self.lineEdit_token.setText("")
        self.lineEdit_token.setEchoMode(QtWidgets.QLineEdit.Password)
        self.lineEdit_token.setObjectName("lineEdit_token")
        self.horizontalLayout_2.addWidget(self.lineEdit_token)
        self.horizontalLayoutWidget_3 = QtWidgets.QWidget(self.groupBox_2)
        self.horizontalLayoutWidget_3.setGeometry(QtCore.QRect(10, 70, 381, 41))
        self.horizontalLayoutWidget_3.setObjectName("horizontalLayoutWidget_3")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_3)
        self.horizontalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label_chat_id = QtWidgets.QLabel(self.horizontalLayoutWidget_3)
        self.label_chat_id.setObjectName("label_chat_id")
        self.horizontalLayout_3.addWidget(self.label_chat_id)
        self.lineEdit_chat_id = QtWidgets.QLineEdit(self.horizontalLayoutWidget_3)
        self.lineEdit_chat_id.setObjectName("lineEdit_chat_id")
        self.horizontalLayout_3.addWidget(self.lineEdit_chat_id)
        self.button_get_chat_id = QtWidgets.QPushButton(self.horizontalLayoutWidget_3)
        self.button_get_chat_id.setObjectName("button_get_chat_id")
        self.horizontalLayout_3.addWidget(self.button_get_chat_id)
        self.label_signed = QtWidgets.QLabel(self.groupBox_2)
        self.label_signed.setGeometry(QtCore.QRect(10, 120, 151, 17))
        self.label_signed.setObjectName("label_signed")
        self.plainTextEdit_signed = QtWidgets.QPlainTextEdit(self.groupBox_2)
        self.plainTextEdit_signed.setGeometry(QtCore.QRect(10, 140, 381, 201))
        self.plainTextEdit_signed.setObjectName("plainTextEdit_signed")
        self.tab_help.addTab(self.tab_2, "")
        self.tab_3 = QtWidgets.QWidget()
        self.tab_3.setObjectName("tab_3")
        self.textEdit = QtWidgets.QTextEdit(self.tab_3)
        self.textEdit.setGeometry(QtCore.QRect(20, 20, 371, 331))
        self.textEdit.setReadOnly(True)
        self.textEdit.setObjectName("textEdit")
        self.tab_help.addTab(self.tab_3, "")
        self.gridLayout_4.addWidget(self.tab_help, 0, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        self.tab_help.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "sender telega "))
        self.label_message.setText(_translate("MainWindow", "сообщение"))
        self.button_send_message.setText(_translate("MainWindow", "отправить сообщение"))
        self.tab_help.setTabText(self.tab_help.indexOf(self.tab), _translate("MainWindow", "сообщение"))
        self.label_token.setText(_translate("MainWindow", "токен:"))
        self.lineEdit_token.setPlaceholderText(_translate("MainWindow", "123456:ABC-DEF1234ghIkl-zyx57W2v1u123ew11"))
        self.label_chat_id.setText(_translate("MainWindow", "канал ид"))
        self.button_get_chat_id.setText(_translate("MainWindow", "получить ид канала"))
        self.label_signed.setText(_translate("MainWindow", "подпись для канала"))
        self.tab_help.setTabText(self.tab_help.indexOf(self.tab_2), _translate("MainWindow", "настройки"))
        self.textEdit.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><meta charset=\"utf-8\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"hr { height: 1px; border-width: 0; }\n"
"</style></head><body style=\" font-family:\'Ubuntu\'; font-size:11pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; line-height:115%; background-color:transparent;\"><span style=\" font-family:\'JetBrains Mono\',\'monospace\'; font-size:12pt; color:#000000;\">Откройте мессенджер Telegram, войдите в вашу учетную запись или создайте новую.</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; line-height:115%; background-color:transparent;\"><span style=\" font-family:\'JetBrains Mono\',\'monospace\'; font-size:12pt; color:#000000;\">1) Создайте Telegram-бота с помощью BotFather</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; line-height:115%; background-color:transparent;\"><span style=\" font-family:\'JetBrains Mono\',\'monospace\'; font-size:12pt; color:#000000;\"><br />Введите в поле поиска </span><span style=\" font-family:\'JetBrains Mono\',\'monospace\'; font-size:12pt; font-style:italic; color:#000000;\">@BotFather</span><span style=\" font-family:\'JetBrains Mono\',\'monospace\'; font-size:12pt; color:#000000;\"> и выберите бота.</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; line-height:115%; background-color:transparent;\"><span style=\" font-family:\'JetBrains Mono\',\'monospace\'; font-size:12pt; color:#000000;\">Нажмите «Запустить» для активации бота BotFather. В ответ вы получите список команд по управлению ботов.<br /><br />Выберите или напечатайте и отправьте команду /newbot.</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; line-height:115%; background-color:transparent;\"><span style=\" font-family:\'JetBrains Mono\',\'monospace\'; font-size:12pt; color:#000000;\">Дайте имя боту — клиенты увидят это имя при общении с ботом. И никнейм бота — по нему можно будет найти бота в Telegram. Никнейм должен быть уникальным, не повторять существующие в базе и заканчиваться на слово «bot». Дайте имя боту — клиенты увидят это имя при общении с ботом. И никнейм бота — по нему можно будет найти бота в Telegram. Никнейм должен быть уникальным, не повторять существующие в базе и заканчиваться на слово «bot».</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; line-height:115%; background-color:transparent;\"><span style=\" font-family:\'JetBrains Mono\',\'monospace\'; font-size:12pt; color:#000000;\">Будет сгенерирован токен для вашего вновь созданного Telegram-бота - он понадобится нам позже.</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; line-height:115%; background-color:transparent;\"><span style=\" font-family:\'JetBrains Mono\',\'monospace\'; font-size:12pt; color:#000000;\">Токен выглядит примерно так: 123456:ABC-DEF1234ghIkl-zyx57W2v1u123ew11</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; line-height:115%; background-color:transparent;\"><span style=\" font-family:\'JetBrains Mono\',\'monospace\'; font-size:12pt; color:#000000;\"><br /></span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; line-height:115%; background-color:transparent;\"><span style=\" font-family:\'JetBrains Mono\',\'monospace\'; font-size:12pt; color:#000000;\">Копируем токен и вставляем в поле «настройки» - «токен»<br /><br /></span><span style=\" font-family:\'JetBrains Mono\',\'monospace\'; font-size:12pt; font-weight:700; color:#000000;\">Примечание: пожалуйста, не сообщайте никому свой токен бота Telegram - любой человек с вашим токеном может получить контроль над вашим ботом Telegram.</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; line-height:115%; background-color:transparent;\"><span style=\" font-family:\'JetBrains Mono\',\'monospace\'; font-size:12pt; color:#000000;\"><br /></span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; line-height:115%; background-color:transparent;\"><span style=\" font-family:\'JetBrains Mono\',\'monospace\'; font-size:12pt; color:#000000;\">2) Создайте чат, содержащий вашего бота</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; line-height:115%; background-color:transparent;\"><span style=\" font-family:\'JetBrains Mono\',\'monospace\'; font-size:12pt; color:#000000;\">Каналы в Телеграме бывают двух видов:</span></p>\n"
"<ol style=\"margin-top: 0px; margin-bottom: 0px; margin-left: 0px; margin-right: 0px; -qt-list-indent: 1;\"><li style=\" font-family:\'JetBrains Mono\',\'monospace\'; font-size:12pt; color:#000000; background-color:transparent;\" style=\" margin-top:12px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; line-height:115%;\"><span style=\" font-size:medium;\">Приватный. Характеризуется лимитированным доступом. Недоступен при поиске. Для вступления подписчику нужно получить ссылку от владельца (администратора). Удобное решение для создания внутрикорпоративных сообществ для информирования сотрудников. В личных целях его можно применять, чтобы писать заметки, шпаргалки. При необходимости приватный канал можно сделать общедоступным. </span></li>\n"
"<li style=\" font-family:\'JetBrains Mono\',\'monospace\'; font-size:12pt; color:#000000; background-color:transparent;\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; line-height:115%;\"><span style=\" font-size:medium;\">Публичный. Доступ к нему есть у всех желающих. Просматривать записи могут даже те пользователи, которые еще не стали подписчиками. Публичный канал доступен в поиске и имеет собственный короткий адрес (ссылку).</span> </li></ol>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; line-height:115%; background-color:transparent;\"><span style=\" font-family:\'JetBrains Mono\',\'monospace\'; font-size:12pt; color:#000000;\">И несколько правил, которые важно учесть перед созданием:</span></p>\n"
"<ul style=\"margin-top: 0px; margin-bottom: 0px; margin-left: 0px; margin-right: 0px; -qt-list-indent: 1;\"><li style=\" font-family:\'JetBrains Mono\',\'monospace\'; font-size:12pt; color:#000000; background-color:transparent;\" style=\" margin-top:12px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; line-height:115%;\"><span style=\" font-size:medium;\">длина логина — 5-32 символа; </span></li>\n"
"<li style=\" font-family:\'JetBrains Mono\',\'monospace\'; font-size:12pt; color:#000000; background-color:transparent;\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; line-height:115%;\"><span style=\" font-size:medium;\">длина названия и bio (описания) — 255 символов; </span></li>\n"
"<li style=\" font-family:\'JetBrains Mono\',\'monospace\'; font-size:12pt; color:#000000; background-color:transparent;\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; line-height:115%;\"><span style=\" font-size:medium;\">предельное количество публичных каналов на один аккаунт — 10; </span></li>\n"
"<li style=\" font-family:\'JetBrains Mono\',\'monospace\'; font-size:12pt; color:#000000; background-color:transparent;\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; line-height:115%;\"><span style=\" font-size:medium;\">количество подписчиков — без ограничений; </span></li>\n"
"<li style=\" font-family:\'JetBrains Mono\',\'monospace\'; font-size:12pt; color:#000000; background-color:transparent;\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; line-height:115%;\"><span style=\" font-size:medium;\">количество подписчиков, видимое владельцу — 200; </span></li>\n"
"<li style=\" font-family:\'JetBrains Mono\',\'monospace\'; font-size:12pt; color:#000000; background-color:transparent;\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; line-height:115%;\"><span style=\" font-size:medium;\">можно привлечь администраторов — до 50; </span></li>\n"
"<li style=\" font-family:\'JetBrains Mono\',\'monospace\'; font-size:12pt; color:#000000; background-color:transparent;\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; line-height:115%;\"><span style=\" font-size:medium;\">можно подключить ботов — до 20; </span></li>\n"
"<li style=\" font-family:\'JetBrains Mono\',\'monospace\'; font-size:12pt; color:#000000; background-color:transparent;\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; line-height:115%;\"><span style=\" font-size:medium;\">право на редактирование контента — до 2-х суток с момента публикации; </span></li>\n"
"<li style=\" font-family:\'JetBrains Mono\',\'monospace\'; font-size:12pt; color:#000000; background-color:transparent;\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; line-height:115%;\"><span style=\" font-size:medium;\">удаление канала с количеством подписчиков от 1 тыс. — только через техподдержку мессенджера.</span> </li></ul>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; line-height:115%; background-color:transparent;\"><span style=\" font-family:\'JetBrains Mono\',\'monospace\'; font-size:12pt; color:#000000;\">Создать канал в Телеграмме можно через десктопное приложение, программы для Android и iOS:</span></p>\n"
"<ul style=\"margin-top: 0px; margin-bottom: 0px; margin-left: 0px; margin-right: 0px; -qt-list-indent: 1;\"><li style=\" font-family:\'JetBrains Mono\',\'monospace\'; font-size:12pt; color:#000000; background-color:transparent;\" style=\" margin-top:12px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; line-height:115%;\"><span style=\" font-size:medium;\">десктоп: нажать в левом углу вверху экрана на три черточки, и в открывшемся меню выбрать «Создать канал»; </span></li>\n"
"<li style=\" font-family:\'JetBrains Mono\',\'monospace\'; font-size:12pt; color:#000000; background-color:transparent;\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; line-height:115%;\"><span style=\" font-size:medium;\">Android: открыть список чатов, нажать на три черточки и выбрать «Новый канал»; </span></li>\n"
"<li style=\" font-family:\'JetBrains Mono\',\'monospace\'; font-size:12pt; color:#000000; background-color:transparent;\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; line-height:115%;\"><span style=\" font-size:medium;\">iOS: во вкладке «Чаты» нажать на иконку нового сообщения в правом углу вверху и выбрать «Новый канал».</span></li></ul>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; line-height:115%; background-color:transparent;\"><span style=\" font-family:\'JetBrains Mono\',\'monospace\'; font-size:12pt; color:#000000;\">Создание и настройку Telegram-канала на десктопном приложении. Вызываем меню:</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; line-height:115%; background-color:transparent;\"><span style=\" font-family:\'JetBrains Mono\',\'monospace\'; font-size:12pt; color:#000000;\">1. Выбираем </span><span style=\" font-family:\'JetBrains Mono\',\'monospace\'; font-size:12pt; font-weight:700; color:#000000;\">«Создать канал»</span><span style=\" font-family:\'JetBrains Mono\',\'monospace\'; font-size:12pt; color:#000000;\">.</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; line-height:115%; background-color:transparent;\"><span style=\" font-family:\'JetBrains Mono\',\'monospace\'; font-size:12pt; color:#000000;\">2. В открывшемся диалоговом окне нужно ввести название и краткое описание</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; line-height:115%; background-color:transparent;\"><span style=\" font-family:\'JetBrains Mono\',\'monospace\'; font-size:12pt; color:#000000;\">3. Следующее диалоговое окно — выбор типа канала. Выбираете публичный, система предложит сформировать ссылку. Вводите варианты названия латиницей. Если ссылка не занята — возникнет соответствующая подсказка.</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; line-height:115%; background-color:transparent;\"><span style=\" font-family:\'JetBrains Mono\',\'monospace\'; font-size:12pt; color:#000000;\">4. На следующем этапе система предложит добавить участников в новый канал из тех, что находятся в ваших контактах. Автору дано право «самовольно» подписать на него до 200 участников из собственных контактов. Можете выбрать отдельных, всех вместе или нажать </span><span style=\" font-family:\'JetBrains Mono\',\'monospace\'; font-size:12pt; font-weight:700; color:#000000;\">«Пропустить»</span><span style=\" font-family:\'JetBrains Mono\',\'monospace\'; font-size:12pt; color:#000000;\">.</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; line-height:115%; background-color:transparent;\"><span style=\" font-family:\'JetBrains Mono\',\'monospace\'; font-size:12pt; color:#000000;\">5. На этом все: канал создан, о чем и уведомит мессенджер. Теперь можно переходить к оформлению и настройкам.</span></p>\n"
"<h2 style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; background-color:transparent;\"><span style=\" font-family:\'Liberation Serif\',\'serif\'; font-size:12pt; font-weight:700; color:#000000;\">Оформление канала Telegram</span></h2>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; line-height:115%; background-color:transparent;\"><span style=\" font-family:\'JetBrains Mono\',\'monospace\'; font-size:12pt; color:#000000;\">Прирост подписчиков, конверсия и другие показатели зависят не только от контента и методов продвижения. Внешний вид тоже имеет значение. Пользователь первоочередно видит картинку канала. Заинтересовавшись, человек переходит и читает описание, а также просматривает несколько сообщений.</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; line-height:115%; background-color:transparent;\"><span style=\" font-family:\'JetBrains Mono\',\'monospace\'; font-size:12pt; color:#000000;\">Главные элементы оформления Телеграм канала — название, описание и аватар (лого, иконка). Начнем с описания. Оно должно быть:</span></p>\n"
"<ul style=\"margin-top: 0px; margin-bottom: 0px; margin-left: 0px; margin-right: 0px; -qt-list-indent: 1;\"><li style=\" font-family:\'JetBrains Mono\',\'monospace\'; font-size:12pt; color:#000000; background-color:transparent;\" style=\" margin-top:12px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; line-height:115%;\"><span style=\" font-size:medium;\">лаконичным; </span></li>\n"
"<li style=\" font-family:\'JetBrains Mono\',\'monospace\'; font-size:12pt; color:#000000; background-color:transparent;\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; line-height:115%;\"><span style=\" font-size:medium;\">ясным; </span></li>\n"
"<li style=\" font-family:\'JetBrains Mono\',\'monospace\'; font-size:12pt; color:#000000; background-color:transparent;\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; line-height:115%;\"><span style=\" font-size:medium;\">максимально раскрывающим суть.</span></li></ul>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; line-height:115%; background-color:transparent;\"><span style=\" font-family:\'JetBrains Mono\',\'monospace\'; font-size:12pt; color:#000000;\">Предельное количество символов, как уже говорилось, — 255. Но лучше уложиться в 200, чтобы био легко можно было прочитать «беглым взглядом». В описании нужно рассказать, о чем канал и дать данные для обратной связи (например, название бота. ссылку на прайс-лист и контакты для заказа рекламы).</span></p>\n"
"<ol style=\"margin-top: 0px; margin-bottom: 0px; margin-left: 0px; margin-right: 0px; -qt-list-indent: 1;\"><li style=\" font-family:\'JetBrains Mono\',\'monospace\'; font-size:12pt; color:#000000; background-color:transparent;\" style=\" margin-top:12px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; line-height:115%;\"><span style=\" font-size:medium;\">Чтобы просмотреть описание, нажмите на меню (три точки справа вверху) и далее — </span><span style=\" font-size:medium; font-weight:700;\">«Описание канала»</span><span style=\" font-size:medium;\">.</span></li></ol>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; line-height:115%; background-color:transparent;\"><span style=\" font-family:\'JetBrains Mono\',\'monospace\'; font-size:12pt; color:#000000;\">Название канала в Telegram нужно написать на языке целевой аудитории. Лучше уложиться в 1-3 слова и указать в названии тематику. Если планируете наращивать аудиторию, которая ищет каналы в поиске Телеграма, добавьте в название ключевые слова.</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; line-height:115%; background-color:transparent;\"><span style=\" font-family:\'JetBrains Mono\',\'monospace\'; font-size:12pt; color:#000000;\">2. Написать или изменить название и описание можно, нажав меню (три точки) и далее </span><span style=\" font-family:\'JetBrains Mono\',\'monospace\'; font-size:12pt; font-weight:700; color:#000000;\">«Управление каналом»</span><span style=\" font-family:\'JetBrains Mono\',\'monospace\'; font-size:12pt; color:#000000;\">.</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; line-height:115%; background-color:transparent;\"><span style=\" font-family:\'JetBrains Mono\',\'monospace\'; font-size:12pt; color:#000000;\">Перейдите в </span><span style=\" font-family:\'JetBrains Mono\',\'monospace\'; font-size:12pt; font-weight:700; color:#000000;\">«Настройки» — «Управление каналом» — «Администраторы» — «Добавить администратора»</span><span style=\" font-family:\'JetBrains Mono\',\'monospace\'; font-size:12pt; color:#000000;\">. В списке подписчиков выбирайте нашего созданного бота и оставить возможности администратора права на </span><span style=\" font-family:\'JetBrains Mono\',\'monospace\'; font-size:12pt; font-weight:700; color:#000000;\">«публикацию сообщений»</span><span style=\" font-family:\'JetBrains Mono\',\'monospace\'; font-size:12pt; color:#000000;\">.</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; line-height:115%; background-color:transparent;\"><span style=\" font-family:\'JetBrains Mono\',\'monospace\'; font-size:12pt; color:#000000;\"><br /></span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; line-height:115%; background-color:transparent;\"><span style=\" font-family:\'JetBrains Mono\',\'monospace\'; font-size:12pt; color:#000000;\">3) получение ид канала</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; line-height:115%; background-color:transparent;\"><span style=\" font-family:\'JetBrains Mono\',\'monospace\'; font-size:12pt; color:#000000;\">Получаем ид канала </span><span style=\" font-family:\'JetBrains Mono\',\'monospace\'; font-size:12pt; font-weight:700; color:#000000;\">«Настройки» — «получить ид канала». </span><span style=\" font-family:\'JetBrains Mono\',\'monospace\'; font-size:12pt; color:#000000;\">Если возникла ошибка пробуем скопировать из описания канала его ссылку и заменить «t.me/» на «@»</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; line-height:115%; background-color:transparent;\"><span style=\" font-family:\'JetBrains Mono\',\'monospace\'; font-size:12pt; color:#000000;\"><br /><br /></span><span style=\" font-family:\'JetBrains Mono\',\'monospace\'; font-size:12pt; font-weight:700; color:#000000;\">Внимание: НЕ позволяйте посторонним лицам получить доступ к вашему токену бота Telegram и НЕ загружайте его в интернет. Любой человек с вашим токеном может получить полный контроль над вашим Telegram-ботом, и вам, вероятно, придется создать нового бота, если это произойдет.</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; line-height:115%; background-color:transparent;\"><span style=\" font-family:\'JetBrains Mono\',\'monospace\'; font-size:12pt; color:#000000;\"><br /><br /></span></p></body></html>"))
        self.tab_help.setTabText(self.tab_help.indexOf(self.tab_3), _translate("MainWindow", "помощь"))
